codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: true

  # We don't want statistics for the tests themselves.
  ignore:
  - .*/tests/.*

comment:
  layout: "header, diff, changes, uncovered"
  behavior: default  # update if exists else create new
