# Customized Bashrc
# Author  : Easwy Yang
# Homepage: http://easwy.com/
# Date    : Mon Oct 25 15:57:42 CST 2010

#set nobeep
#xset b off
setterm -blength 0

# use vi mode
set -o vi

# Useful alias
alias .ee='vi ~/.bashrc'
alias .ss='source ~/.bashrc'

PS1='\[\033[0;32m\]\u\[\033[00m\]@\[\033[0;32m\]\h\[\033[00m\] \W> '
export PS1

#PROMPT_COMMAND='\[\033[0;32m\]\u\[\033[00m\]@\[\033[0;32m\]\h\[\033[00m\] \W> '
#export PROMPT_COMMAND

